### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by brunomiguel** [NoahBuscher/Spigot#4]
Spigot lacks an icon and every app should have one. ;)

I would like to help create it, but I would first need to know what's the specific meaning for spigot in this case and what you want for the app.

**Comment by noahbuscher** [comment]
Haha! I just saw this issue again. Tried to push a commit, but I didn't do any testing. :stuck_out_tongue_closed_eyes: 0b176278d18b3e228584828c6fc3efa0df8eb131
